Themes color and variables
samrith-s/sticky-react-table pull request #12
Opened 2018-08-23 05:12 UTC by sonAndrew

Hey, @samith-s , I only had time to fix :

1. **theme variables** 
2. **dark theme colors**

Inside the **_src/themes_** folder : 

> I created a folder for **partials** 
> Inside partials a folder for **variables**

Inside **_/themes/partials/variables_** folder :

> I created files for each dark and light variables

<img width="270" alt="screenshot 2018-08-23 01 02 06" src="https://user-images.githubusercontent.com/25195944/44505659-9b7cde80-a670-11e8-8c7b-fd1ea3448c90.png">

Inside the **_themes/dark.scss_** file : 
> Imported /partials/variables/_dark-variables

<img width="676" alt="screenshot 2018-08-23 01 03 02" src="https://user-images.githubusercontent.com/25195944/44505717-e139a700-a670-11e8-9d28-a56c78f7a247.png">

Inside the **_themes/light.scss_** file : 
> Imported /partials/variables/_light-variables

<img width="435" alt="screenshot 2018-08-23 01 02 20" src="https://user-images.githubusercontent.com/25195944/44505692-c6ffc900-a670-11e8-8fec-43c11c254949.png">

2018-08-23 09:34 UTC, samrith-s commented
@sonAndrew Hey, there is a build error. Please check it out once. Will review once the build succeeds. I think the import path for dark-variables is incorrect.

2018-08-24 03:49 UTC, sonAndrew commented
Hey, @samrith-s I checked to see if the dark theme worked but because of the fix to the variable names and colors, it gives a weird offset that doesn't look like the file attached on GitHub
<img width="1310" alt="screenshot 2018-08-23 23 45 20" src="https://user-images.githubusercontent.com/25195944/44563973-c4fc3f80-a72e-11e8-833f-449e6aec7444.png">
.

2018-08-24 04:02 UTC, sonAndrew commented
Hey, @samrith-s I checked to see if the dark theme worked but because of the fix to the variable names and colors, it gives a weird offset that doesn't look like the file attached on GitHub. If you can tell me what you want each to be I will fix it. I have a color palette on codepen. Click [HERE](https://codepen.io/Atsui-yo/pen/mGJpqq) !

2018-08-24 11:47 UTC, samrith-s requested changes
@sonAndrew I'm a bit confused by this. What exactly is the *offset* you are talking about?

Also, please remove `package-lock.json`. We are using `yarn` for this project not `npm`.

2018-08-24 11:47 UTC, samrith-s commented on src/themes/partials/variables/_dark-variables.scss
> +$dark: #222222;
Do a check of the variables. The dark theme looks like a light theme with a mix of dark backgrounds. Please verify this.

2018-08-24 11:47 UTC, samrith-s commented on src/themes/partials/variables/_light-variables.scss
> +$interaction: #add8e6;
This either has to be `interaction-color` or all dependencies in the light theme stylesheet have to be changed to `interaction`. It throws an error when you use the light theme.

Please check it thoroughly for both themes.

2018-08-27 21:15 UTC, samrith-s approved these changes
Looks good!

2018-08-27 21:15 UTC, merged