Basic implementation of column reordering
samrith-s/sticky-react-table pull request #20
Opened 2018-08-29 09:42 UTC by kumarankit1234

i. Reordering of columns

2018-08-30 08:28 UTC, samrith-s commented
@kumarankit1234 Let's implement this using https://github.com/atlassian/react-beautiful-dnd

This will help us with a lot of stuff, and also in column-resizing.

2018-08-30 09:21 UTC, dmitriy-kudelko requested changes
@kumarankit1234 , I think it'd be cool to do a couple of more things:
- to add a mechanism to prevent re-ordering of certain columns (such as checkbox column for instance). This can be done by providing a certain prop: e.g `reordarable={false}`
- to disable vertical movement while dragging (only allow x axis)
- to drag the whole column rather than just the header
- to add some custom icon/cursor indicating that a column is draggable. Not sure what's the best way to do this, but currently it's difficult to guess that a column can be re-ordered.

2018-08-30 09:21 UTC, dmitriy-kudelko commented on src/components/Rows/Cells/HeaderCell.js
> +        draggable={true}
Very minor: passing true is redundant.

2018-08-30 10:01 UTC, kumarankit1234 commented
@samrith-s 
> We either use that, or if we do not want to use additional packages, we should clone the element rather than using native ghost preview.

Currently we are not showing any preview of the column being reordered. That I will do later once the basic integration of reordering is done with the existing Table.

2018-08-30 10:03 UTC, kumarankit1234 commented
@dmitriy-kudelko 
> to add a mechanism to prevent re-ordering of certain columns (such as checkbox column for instance). This can be done by providing a certain prop: e.g reordable={false}

This will prevent a column from being reordered. But what will happen in the case when reordering of other columns will have to reorder a column whose reordable={false} is set.?

2018-08-30 10:07 UTC, dmitriy-kudelko commented
@kumarankit1234 ,

> This will prevent a column from being reordered. But what will happen in the case when reordering of other columns will have to reorder a column whose reordable={false} is set.?

I think what should happen is that when you drag any other column over a not re-ordarable one, the cursor should change to disabled and drop event shouldn't fire.

2018-08-30 11:11 UTC, kumarankit1234 commented
@dmitriy-kudelko As discussed with @samrith-s For now if we are not allowing reOrderable props. For now we will prevent the reodering of the first column if it is a checkbox column. Later we will think of a better way to handle reordering of columns when one of them has reOrderable false.

2018-08-30 11:39 UTC, kumarankit1234 commented
Also 
> to drag the whole column rather than just the header

Not an important requirement for now. Will do this later.

2018-09-03 07:04 UTC, samrith-s approved these changes
Basic implementation looks good.

2018-09-03 07:24 UTC, merged