Basic implementation of column max resize on double click
samrith-s/sticky-react-table pull request #21
Opened 2018-08-29 11:23 UTC by kumarankit1234

i. Resize the column to it's max width on double click.

2018-08-30 08:35 UTC, samrith-s commented
One basic error which I can observe, is that whenever you click on it, it sorts before resizing. Please look into that.

2018-08-30 09:06 UTC, dmitriy-kudelko requested changes
@kumarankit1234 , please see comments.

Also by now the mechanism doesn't seem top be working well:
- If you reduce the width of Phone column by half and try to auto resize, nothing will happen
- If you do the opposite and increase its width then column won't be auto adjusted to a minimal required width either.

2018-08-30 09:06 UTC, dmitriy-kudelko commented on src/components/Table.js
> +    const columnDivs = document.getElementsByClassName(
This is not reliable. There might be more than one table on a page.

2018-08-30 09:06 UTC, dmitriy-kudelko commented on src/components/Table.js
> +    maxWidth = Array.prototype.reduce.call(
You could possibly just spread columnDivs instead of doing this by means of Array.prototype.

2018-08-30 09:06 UTC, dmitriy-kudelko commented on src/components/Table.js
> +  handleMaxColumnResize = cellIndex => {
I would say that the method name (and all related props) doesn't really reflect the meaning. We're not resizing to max width, we're adjusting the width to a minimal required value to see contents of all cells. So let's maybe operate with "auto resize" or something more meaningful.

2018-08-30 09:06 UTC, dmitriy-kudelko commented on src/components/Table.js
> +    const columnDivs = document.getElementsByClassName(
What if we change divs to spans in the markup?

2018-08-30 09:06 UTC, dmitriy-kudelko commented on src/components/Table.js
> +    columns.splice(cellIndex, 1, resizedColumn);
Let's perform a precise update of just column width instead of replacing the column itself.

2018-08-30 09:06 UTC, kumarankit1234 commented
@samrith-s That will be fixed when this is merged. https://github.com/samrith-s/sticky-react-table/pull/19/files#diff-40d712379ef434e2e2e2acfe4703ae89R54

2018-09-03 06:55 UTC, kumarankit1234 commented on src/components/Table.js
> +    maxWidth = Array.prototype.reduce.call(
`[...columnDivs].reduce (() => {maxWidth, cell} , maxWidth)`

It throws an error when I try to access cell.outerHTML

2018-09-03 07:07 UTC, samrith-s approved these changes
Looks from my side.

2018-09-03 07:08 UTC, merged